---
title: Updating the FormatOverview document 
# format: docx
---

```{r setup, echo=FALSE}
source("../common.R")
```


<!-- output for regular document  -->

<!-- ```{r} -->

<!-- json = rjson::fromJSON(file = "portable_microhaplotype_object.schema.json") -->


<!-- outputFile = "generated_FormatExample_subsection_descriptions.txt" -->

<!-- cat("", file = outputFile) -->

<!-- for(subclass in names(json$`$defs`)){ -->

<!--   cat(paste0("\n## ", subclass, "  \n"), sep = "",file = outputFile, append = T) -->
<!--   cat(paste0("<https://plasmogenepi.github.io/portable-microhaplotype-object/", subclass, "/>  "), "\n", sep = "",file = outputFile, append = T) -->

<!--   cat("\n### Required  ", "\n", sep = "",file = outputFile, append = T) -->
<!--   for(prop in json$`$defs`[[subclass]]$required){ -->
<!--       if("$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]])){ -->
<!--          type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$`$ref`)  -->
<!--          cat(paste0("*  ", prop, " (***type=","[", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--       } else if("array" == json$`$defs`[[subclass]]$properties[[prop]]$type){ -->
<!--         if("$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]]$items)){ -->
<!--           type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$items$`$ref`)  -->
<!--           cat(paste0("*  ", prop, " (***type=","[", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--         } else {  -->
<!--            cat(paste0("*  ", prop, " (***type=", json$`$defs`[[subclass]]$properties[[prop]]$type, "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--         } -->
<!--       } else {  -->
<!--          cat(paste0("*  ", prop, " (***type=", json$`$defs`[[subclass]]$properties[[prop]]$type, "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--       } -->
<!--       cat(paste0("    *  ", json$`$defs`[[subclass]]$properties[[prop]]$description), "  \n", sep = "",file = outputFile, append = T) -->
<!--   } -->

<!--   optional = names(json$`$defs`[[subclass]]$properties)[names(json$`$defs`[[subclass]]$properties) %!in% json$`$defs`[[subclass]]$required] -->
<!--   if (length(optional) > 0) { -->
<!--     cat("\n### Optional  ", "\n", sep = "",file = outputFile, append = T) -->
<!--     for (prop in optional) { -->
<!--       if("$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]])){ -->
<!--          type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$`$ref`)  -->
<!--          cat(paste0("*  ", prop, " (***type=","[", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--       } else if("array" == json$`$defs`[[subclass]]$properties[[prop]]$type){ -->
<!--         if("$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]]$items)){ -->
<!--           type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$items$`$ref`)  -->
<!--           cat(paste0("*  ", prop, " (***type=","[", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--         } else {  -->
<!--            cat(paste0("*  ", prop, " (***type=", json$`$defs`[[subclass]]$properties[[prop]]$type, "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--         } -->
<!--       } else {  -->
<!--          cat(paste0("*  ", prop, " (***type=", json$`$defs`[[subclass]]$properties[[prop]]$type, "***)"), "  \n", sep = "",file = outputFile, append = T) -->
<!--       } -->
<!--       cat(paste0("    *  ", json$`$defs`[[subclass]]$properties[[prop]]$description), "  \n", sep = "",file = outputFile, append = T) -->
<!--     } -->
<!--   } -->

<!--   cat("\n### Example  ", "\n" , -->
<!--       "```{json}  ", "\n" ,  -->
<!--       "", "\n" ,  -->
<!--       "```  ", "\n" ,  -->
<!--       sep = "",file = outputFile, append = T) -->






<!--   cat("\n", sep = "",file = outputFile, append = T) -->
<!-- } -->



<!-- ``` -->



outputing with collapsible content 

```{r}

json = rjson::fromJSON(file = "portable_microhaplotype_object.schema.json")


outputFile = "generated_FormatExample_subsection_descriptions_collapsible.txt"

cat("", file = outputFile)

for(subclass in names(json$`$defs`)){
  
  cat(paste0("\n## ", subclass, "  \n"), sep = "",file = outputFile, append = T)
  cat(paste0("<https://plasmogenepi.github.io/portable-microhaplotype-object/", subclass, "/>  "), "\n", sep = "",file = outputFile, append = T)
  cat(paste0("<a class = \"btn btn-light\" data-bs-toggle=\"collapse\" data-bs-target=\"#collapse", subclass, "\" aria-expanded=\"true\" aria-controls=\"collapseExample\">
  Show ", subclass, " fields <i class=\"fa-solid fa-caret-right\"></i>
</a>
<div class=\"collapse show\" id=\"collapse", subclass, "\">
  <div class=\"card card-body\">"
  ), sep = "",file = outputFile, append = T)

  cat("\n### Required  ", "\n", sep = "",file = outputFile, append = T)
  for(prop in json$`$defs`[[subclass]]$required){
      if("$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]])){
         type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$`$ref`) 
         cat(paste0("*  ", prop, " (***type=","[", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T)
      } else if("array" == json$`$defs`[[subclass]]$properties[[prop]]$type){
        if("$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]]$items)){
          type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$items$`$ref`) 
          cat(paste0("*  ", prop, " (***type=","[list of ", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T)
        } else { 
           cat(paste0("*  ", prop, " (***type= list of ", json$`$defs`[[subclass]]$properties[[prop]]$items$type[1], "***)"), "  \n", sep = "",file = outputFile, append = T)
        }
      } else { 
         cat(paste0("*  ", prop, " (***type=", json$`$defs`[[subclass]]$properties[[prop]]$type, "***)"), "  \n", sep = "",file = outputFile, append = T)
      }
      cat(paste0("    *  ", json$`$defs`[[subclass]]$properties[[prop]]$description), "  \n", sep = "",file = outputFile, append = T)
  }
  
  optional = names(json$`$defs`[[subclass]]$properties)[names(json$`$defs`[[subclass]]$properties) %!in% json$`$defs`[[subclass]]$required]
  if (length(optional) > 0) {
    cat("\n### Optional  ", "\n", sep = "",file = outputFile, append = T)
    for (prop in optional) {
      if("anyOf" %in% names(json$`$defs`[[subclass]]$properties[[prop]]) && "$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]]$anyOf[[1]])){
         type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$anyOf[[1]]$`$ref`) 
         cat(paste0("*  ", prop, " (***type=","[", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T)
      } else if("array" == json$`$defs`[[subclass]]$properties[[prop]]$type[1]){
        if("$ref" %in% names(json$`$defs`[[subclass]]$properties[[prop]]$items)){
          type = gsub(".*\\/", "", json$`$defs`[[subclass]]$properties[[prop]]$items$`$ref`) 
          cat(paste0("*  ", prop, " (***type=","[", "list of ", type, "]","(#", tolower(type), ")" , "***)"), "  \n", sep = "",file = outputFile, append = T)
        } else { 
          cat(paste0("*  ", prop, " (***type=", "list of ", json$`$defs`[[subclass]]$properties[[prop]]$items$type[1], "***)"), "  \n", sep = "",file = outputFile, append = T)
        }
      } else { 
         cat(paste0("*  ", prop, " (***type=", json$`$defs`[[subclass]]$properties[[prop]]$type[1], "***)"), "  \n", sep = "",file = outputFile, append = T)
      }
      cat(paste0("    *  ", json$`$defs`[[subclass]]$properties[[prop]]$description), "  \n", sep = "",file = outputFile, append = T)
    }
  }
  cat("\n### Example  ", "\n" ,
      "```{json}  ", "\n" , 
      "", "\n" , 
      "```  ", "\n" , 
      sep = "",file = outputFile, append = T)
  cat(paste0("  </div>
</div><br>"
  ), sep = "",file = outputFile, append = T)
  cat("\n", sep = "",file = outputFile, append = T)
}

cat("\n{{< fa dna >}}\n", sep = "",file = outputFile, append = T)

```




```{r}
pmo_schema_json = rjson::fromJSON(file = "portable_microhaplotype_object.schema.json")

outputFile = "portable_microhaplotype_object.schema.dot"

cat("", file = outputFile)
cat("digraph PMO {
	graph [
		label = \"PMO\\n\\n\"
		labelloc = t
		fontname = \"Helvetica,Arial,sans-serif\"
		fontsize = 20
		layout = dot
		rankdir = LR
		newrank = true
		splines=polyline
    ranksep=1.5
    nodesep=0.4
	]
	node [
		style=filled
		shape=rect
		pencolor=\"#00000044\" // frames color
		fontname=\"Helvetica,Arial,sans-serif\"
		shape=plaintext
	]
	edge [
		arrowsize=0.5
		fontname=\"Helvetica,Arial,sans-serif\"
		labeldistance=3
		labelfontcolor=\"#00000080\"
		penwidth=2
		style=solid 
	]
",file = outputFile, append = T)
colorPalette_15 = c("#F60239","#003C86","#EF0096","#9400E6","#009FFA","#008169","#68023F","#00DCB5","#FFCFE2","#FF71FD","#7CFFFA","#6A0213","#008607","#00E307","#FFDC3D")


type_colors = c("integer" = "#009FFA", "number" = "#00E307", "string" = "#FFDC3D", "boolean" = "#EF0096")
list_or_single_value_colors = c("list" = "#FF71FD", "single" = "#7CFFFA")
# add nodes 
for(pmo_class in pmo_schema_json$`$defs`){
  cat(paste0("	", pmo_class$title, "_NODE [ \n"),file = outputFile, append = T)
  cat("		label=<<table border=\"0\" cellborder=\"1\" cellspacing=\"0\" cellpadding=\"3\">\n",file = outputFile, append = T)
  cat(paste0("			<tr> <td bgcolor=\"#FFCFE2\" port=\"", pmo_class$title, "\"><b>", pmo_class$title, "</b> </td> <td></td> <td></td> </tr>\n"),file = outputFile, append = T)
  cat(paste0("			<tr> <td><b>type</b></td><td><b>list<br/>or<br/>single value</b></td><td ><b>fields</b></td> </tr>\n"),file = outputFile, append = T)
  cat(paste0("			<tr> <td></td><td></td><td ><b>required</b></td> </tr>\n"),file = outputFile, append = T)

  for(required in pmo_class$required){
    type = NA
    list_or_single_value = NA
    if("$ref" %in% names(pmo_class$properties[[required]])){
      list_or_single_value = "single"
      type = gsub(".*\\/", "", pmo_class$properties[[required]]$`$ref`)
    } else if (pmo_class$properties[[required]]$type == "array" && "$ref" %in% names(pmo_class$properties[[required]]$items)){
      list_or_single_value = "list"
      type = gsub(".*\\/", "", pmo_class$properties[[required]]$items$`$ref`)
    } else if (pmo_class$properties[[required]]$type == "array" && "type" %in% names(pmo_class$properties[[required]]$items)){
      list_or_single_value = "list"
      type = pmo_class$properties[[required]]$items$type
    } else if ("type" %in% names(pmo_class$properties[[required]])){
      list_or_single_value = "single"
      type = pmo_class$properties[[required]]$type
    }
    bg = "#FFCFE2"
    if(type %in% names(type_colors)){
      bg = as.character(type_colors[type])
    }
    cat(paste0("			<tr> <td bgcolor=\"", bg, "\">", type, "</td><td bgcolor=\"", list_or_single_value_colors[list_or_single_value], "\">", list_or_single_value, "</td> <td port=\"", required, "\" bgcolor=\"#F60239\">", required, "</td> </tr>\n"),file = outputFile, append = T)
  }
  non_required_props = c()
  for(prop in names(pmo_class$properties)){
    if(prop %!in% pmo_class$required){
      non_required_props = c(non_required_props, prop)
    }
  }
  if(length(non_required_props) > 0){
    cat(paste0("			<tr> <td></td><td></td> <td><b>optional</b></td> </tr>\n"),file = outputFile, append = T)
    for(non_required in non_required_props){
      type = NA
      list_or_single_value = NA
      if("anyOf" %in% names(pmo_class$properties[[non_required]]) && "$ref" %in% names(pmo_class$properties[[non_required]]$anyOf[[1]])){
        list_or_single_value = "single"
        type = gsub(".*\\/", "", pmo_class$properties[[non_required]]$anyOf[[1]]$`$ref`)
      } else if (pmo_class$properties[[non_required]]$type[1] == "array" && "$ref" %in% names(pmo_class$properties[[non_required]]$items)){
        list_or_single_value = "list"
        type = gsub(".*\\/", "", pmo_class$properties[[non_required]]$items$`$ref`)
      } else if (pmo_class$properties[[non_required]]$type[1] == "array" && "type" %in% names(pmo_class$properties[[non_required]]$items)){
        list_or_single_value = "list"
        type = pmo_class$properties[[non_required]]$items$type[1]
      } else if ("type" %in% names(pmo_class$properties[[non_required]])){
        list_or_single_value = "single"
        type = pmo_class$properties[[non_required]]$type[1]
      }
      bg = "#FFCFE2"
      if(type %in% names(type_colors)){
        bg = as.character(type_colors[type])
      }
      cat(paste0("			<tr> <td bgcolor=\"", bg, "\">", type, "</td><td bgcolor=\"", list_or_single_value_colors[list_or_single_value], "\">", list_or_single_value, "</td> <td port=\"", non_required, "\" bgcolor=\"#00DCB5\">", non_required, "</td> </tr>\n"), file = outputFile, append = T)
    }
  }
  cat("		</table>>
		shape=plain		
	]\n", file = outputFile, append = T)
}

# edges 
for(pmo_class in pmo_schema_json$`$defs`){
  for(prop in names(pmo_class$properties)){
    # check if type is 
    if("$ref" %in% names(pmo_class$properties[[prop]])){
      cat(paste0("	", pmo_class$title, "_NODE:", prop, " -> ", gsub(".*\\/", "", pmo_class$properties[[prop]]$`$ref`), "_NODE:", gsub(".*\\/", "", pmo_class$properties[[prop]]$`$ref`), "\n"),
          file = outputFile, append = T)
    } else if("anyOf" %in% names(pmo_class$properties[[prop]]) && "$ref" %in% names(pmo_class$properties[[prop]]$anyOf[[1]])){
      cat(paste0("	", pmo_class$title, "_NODE:", prop, " -> ", gsub(".*\\/", "", pmo_class$properties[[prop]]$anyOf[[1]]$`$ref`), "_NODE:", gsub(".*\\/", "", pmo_class$properties[[prop]]$anyOf[[1]]$`$ref`), "\n"),
          file = outputFile, append = T)
    } else if (pmo_class$properties[[prop]]$type[1] == "array" && "$ref" %in% names(pmo_class$properties[[prop]]$items)){
      cat(paste0("	", pmo_class$title, "_NODE:", prop, " -> ", gsub(".*\\/", "", pmo_class$properties[[prop]]$items$`$ref`), "_NODE:", gsub(".*\\/", "", pmo_class$properties[[prop]]$items$`$ref`), "\n"),
          file = outputFile, append = T)
    }
  }
}

cat("}\n",file = outputFile, append = T)
```


